####################################################################
# Licensed Materials Property of HCL
# (c) Copyright HCL Technologies Ltd. 2020. All rights reserved.
# 
# Trademark of HCL Technologies Limited
####################################################################
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: itx-rs-network-policy
  labels:
{{ include "itx.rs.labels" . | indent 4 }}
spec:
  policyTypes:
  - Ingress
  podSelector:
    matchLabels:
{{ include "itx.rs.labels" . | indent 6 }}
  ingress:
  - ports:
    {{- if .Values.ssl.enabled }}
    - protocol: TCP
      port: 8443
    {{- else }}
    - protocol: TCP
      port: 8080
    {{- end}}
