####################################################################
# Licensed Materials Property of HCL
# (c) Copyright HCL Technologies Ltd. 2021. All rights reserved.
# 
# Trademark of HCL Technologies Limited
####################################################################
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.general.serviceAccountName }}
  labels:
{{ include "itx.rs.labels" . | indent 4 }}
imagePullSecrets:
  - name: sa-{{ .Release.Namespace }}
  {{- if .Values.image.secret }}
  - name: {{ .Values.image.secret }}
  {{- end }}
